//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyDontu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDontu
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string Noidung { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> FK_LoaiDonTuID { get; set; }
        public Nullable<int> FK_NhanvienID { get; set; }
        public Nullable<int> FK_SinhvienID { get; set; }
        public string Trangthai { get; set; }
    
        public virtual tblLoaiDontu tblLoaiDontu { get; set; }
        public virtual tblNhanvien tblNhanvien { get; set; }
        public virtual tblSinhvien tblSinhvien { get; set; }
    }
}
