//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyDontu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoaiDontu
    {
        public tblLoaiDontu()
        {
            this.tblDontus = new HashSet<tblDontu>();
        }
    
        public int ID { get; set; }
        public string TenLoai { get; set; }
    
        public virtual ICollection<tblDontu> tblDontus { get; set; }
    }
}
