//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyDontu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhongban
    {
        public tblPhongban()
        {
            this.tblNhanviens = new HashSet<tblNhanvien>();
        }
    
        public int ID { get; set; }
        public string Ma_phong_ban { get; set; }
        public string Ten_phong_ban { get; set; }
    
        public virtual ICollection<tblNhanvien> tblNhanviens { get; set; }
    }
}
